<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CaptchaSettingsController;
use App\Http\Controllers\ChallanController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\DivisionController;
use App\Http\Controllers\OperatorController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\FareController;
use App\Http\Controllers\GrantController;
use App\Http\Controllers\GrantReleaseController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RootRedirectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SecurityLogController;
use App\Http\Controllers\TransportRouteController;
use App\Http\Controllers\TripDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\VehicleTypeController;
use Illuminate\Support\Facades\Route;

Route::get('/', RootRedirectController::class)->name('home');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'create'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->name('login.store');
});

Route::middleware('auth')->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/users/all', [UserController::class, 'index'])->name('users.all');
    Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
    Route::post('/users', [UserController::class, 'store'])->name('users.store');
    Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::put('/users/{user}/password', [UserController::class, 'updatePassword'])->name('users.password.update');
    Route::delete('/users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::get('/trips', [TripDetailController::class, 'index'])->name('trips.index');
    Route::get('/trips/create', [TripDetailController::class, 'create'])->name('trips.create');
    Route::get('/trips/vehicle-details', [TripDetailController::class, 'vehicleDetails'])->name('trips.vehicle-details');
    Route::get('/trips/route-details', [TripDetailController::class, 'routeDetails'])->name('trips.route-details');
    Route::get('/trips/export/csv', [TripDetailController::class, 'exportCsv'])->name('trips.export.csv');
    Route::get('/trips/export/excel', [TripDetailController::class, 'exportExcel'])->name('trips.export.excel');
    Route::get('/trips/export/pdf-view', [TripDetailController::class, 'pdfView'])->name('trips.export.pdf-view');
    Route::post('/trips', [TripDetailController::class, 'store'])->name('trips.store');
    Route::get('/trips/{trip}', [TripDetailController::class, 'show'])->name('trips.show');
    Route::get('/trips/{trip}/edit', [TripDetailController::class, 'edit'])->name('trips.edit');
    Route::put('/trips/{trip}', [TripDetailController::class, 'update'])->name('trips.update');
    Route::delete('/trips/{trip}', [TripDetailController::class, 'destroy'])->name('trips.destroy');
    Route::get('/payments', [PaymentController::class, 'index'])->name('payments.index');
    Route::get('/payments/due', [PaymentController::class, 'due'])->name('payments.due');
    Route::get('/payments/approved', [PaymentController::class, 'approved'])->name('payments.approved');
    Route::get('/payments/paid', [PaymentController::class, 'paid'])->name('payments.paid');
    Route::get('/payments/on-hold', [PaymentController::class, 'onHold'])->name('payments.on-hold');
    Route::get('/payments/rejected', [PaymentController::class, 'rejected'])->name('payments.rejected');
    Route::get('/payments/export/csv', [PaymentController::class, 'exportCsv'])->name('payments.export.csv');
    Route::get('/payments/export/excel', [PaymentController::class, 'exportExcel'])->name('payments.export.excel');
    Route::get('/payments/export/pdf-view', [PaymentController::class, 'pdfView'])->name('payments.export.pdf-view');
    Route::get('/payments/export/pdf-table-view', [PaymentController::class, 'pdfTableView'])->name('payments.export.pdf-table-view');
    Route::patch('/payments/bulk-approve', [PaymentController::class, 'bulkApprove'])->name('payments.bulk-approve');
    Route::get('/payments/{payment}', [PaymentController::class, 'show'])->name('payments.show');
    Route::patch('/payments/{payment}/approve', [PaymentController::class, 'approve'])->name('payments.approve');
    Route::patch('/payments/{payment}/hold', [PaymentController::class, 'hold'])->name('payments.hold');
    Route::patch('/payments/{payment}/reject', [PaymentController::class, 'reject'])->name('payments.reject');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/export/csv', [ReportController::class, 'exportCsv'])->name('reports.export.csv');
    Route::get('/reports/export/excel', [ReportController::class, 'exportExcel'])->name('reports.export.excel');
    Route::get('/reports/export/pdf-view', [ReportController::class, 'pdfView'])->name('reports.export.pdf-view');
    Route::get('/challans', [ChallanController::class, 'index'])->name('challans.index');
    Route::get('/challans/create', [ChallanController::class, 'create'])->name('challans.create');
    Route::get('/challans/route-details', [ChallanController::class, 'routeDetails'])->name('challans.route-details');
    Route::post('/challans', [ChallanController::class, 'store'])->name('challans.store');
    Route::get('/challans/{challan}/attachment', [ChallanController::class, 'attachment'])->name('challans.attachment');
    Route::get('/challans/{challan}', [ChallanController::class, 'show'])->name('challans.show');
    Route::get('/challans/{challan}/edit', [ChallanController::class, 'edit'])->name('challans.edit');
    Route::put('/challans/{challan}', [ChallanController::class, 'update'])->name('challans.update');
    Route::delete('/challans/{challan}', [ChallanController::class, 'destroy'])->name('challans.destroy');
    Route::redirect('/operators', '/transporters');
    Route::get('/transporters', [OperatorController::class, 'index'])->name('transporters.index');
    Route::get('/transporters/create', [OperatorController::class, 'create'])->name('transporters.create');
    Route::get('/transporters/export/csv', [OperatorController::class, 'exportCsv'])->name('transporters.export.csv');
    Route::get('/transporters/export/excel', [OperatorController::class, 'exportExcel'])->name('transporters.export.excel');
    Route::get('/transporters/export/pdf-view', [OperatorController::class, 'pdfView'])->name('transporters.export.pdf-view');
    Route::post('/transporters', [OperatorController::class, 'store'])->name('transporters.store');
    Route::get('/transporters/{operator}', [OperatorController::class, 'show'])->name('transporters.show');
    Route::get('/transporters/{operator}/edit', [OperatorController::class, 'edit'])->name('transporters.edit');
    Route::put('/transporters/{operator}', [OperatorController::class, 'update'])->name('transporters.update');
    Route::delete('/transporters/{operator}', [OperatorController::class, 'destroy'])->name('transporters.destroy');
    Route::redirect('/transport-routes', '/routes');
    Route::get('/routes', [TransportRouteController::class, 'index'])->name('routes.index');
    Route::get('/routes/create', [TransportRouteController::class, 'create'])->name('routes.create');
    Route::post('/routes', [TransportRouteController::class, 'store'])->name('routes.store');
    Route::get('/routes/{transportRoute}', [TransportRouteController::class, 'show'])->name('routes.show');
    Route::get('/routes/{transportRoute}/edit', [TransportRouteController::class, 'edit'])->name('routes.edit');
    Route::put('/routes/{transportRoute}', [TransportRouteController::class, 'update'])->name('routes.update');
    Route::delete('/routes/{transportRoute}', [TransportRouteController::class, 'destroy'])->name('routes.destroy');
    Route::get('/vehicles', [VehicleController::class, 'index'])->name('vehicles.index');
    Route::get('/vehicles/create', [VehicleController::class, 'create'])->name('vehicles.create');
    Route::get('/vehicles/export/csv', [VehicleController::class, 'exportCsv'])->name('vehicles.export.csv');
    Route::get('/vehicles/export/excel', [VehicleController::class, 'exportExcel'])->name('vehicles.export.excel');
    Route::get('/vehicles/export/pdf-view', [VehicleController::class, 'pdfView'])->name('vehicles.export.pdf-view');
    Route::post('/vehicles', [VehicleController::class, 'store'])->name('vehicles.store');
    Route::get('/vehicles/types', [VehicleTypeController::class, 'index'])->name('vehicles.types.index');
    Route::post('/vehicles/types', [VehicleTypeController::class, 'store'])->name('vehicles.types.store');
    Route::get('/vehicles/types/{vehicleType}/edit', [VehicleTypeController::class, 'edit'])->name('vehicles.types.edit');
    Route::put('/vehicles/types/{vehicleType}', [VehicleTypeController::class, 'update'])->name('vehicles.types.update');
    Route::delete('/vehicles/types/{vehicleType}', [VehicleTypeController::class, 'destroy'])->name('vehicles.types.destroy');
    Route::get('/vehicles/{vehicle}', [VehicleController::class, 'show'])->name('vehicles.show');
    Route::get('/vehicles/{vehicle}/edit', [VehicleController::class, 'edit'])->name('vehicles.edit');
    Route::put('/vehicles/{vehicle}', [VehicleController::class, 'update'])->name('vehicles.update');
    Route::delete('/vehicles/{vehicle}', [VehicleController::class, 'destroy'])->name('vehicles.destroy');
    Route::get('/fares', [FareController::class, 'index'])->name('fares.index');
    Route::get('/fares/create', [FareController::class, 'create'])->name('fares.create');
    Route::post('/fares', [FareController::class, 'store'])->name('fares.store');
    Route::get('/fares/{fare}', [FareController::class, 'show'])->name('fares.show');
    Route::get('/fares/{fare}/edit', [FareController::class, 'edit'])->name('fares.edit');
    Route::put('/fares/{fare}', [FareController::class, 'update'])->name('fares.update');
    Route::delete('/fares/{fare}', [FareController::class, 'destroy'])->name('fares.destroy');
    Route::get('/grants', [GrantController::class, 'index'])->name('grants.index');
    Route::get('/grants/create', [GrantController::class, 'create'])->name('grants.create');
    Route::post('/grants', [GrantController::class, 'store'])->name('grants.store');
    Route::get('/grants/{grant}', [GrantController::class, 'show'])->name('grants.show');
    Route::get('/grants/{grant}/edit', [GrantController::class, 'edit'])->name('grants.edit');
    Route::put('/grants/{grant}', [GrantController::class, 'update'])->name('grants.update');
    Route::delete('/grants/{grant}', [GrantController::class, 'destroy'])->name('grants.destroy');
    Route::get('/grant-releases', [GrantReleaseController::class, 'index'])->name('grant-releases.index');
    Route::get('/grant-releases/create', [GrantReleaseController::class, 'create'])->name('grant-releases.create');
    Route::post('/grant-releases', [GrantReleaseController::class, 'store'])->name('grant-releases.store');
    Route::get('/grant-releases/{grantRelease}', [GrantReleaseController::class, 'show'])->name('grant-releases.show');
    Route::get('/grant-releases/{grantRelease}/edit', [GrantReleaseController::class, 'edit'])->name('grant-releases.edit');
    Route::put('/grant-releases/{grantRelease}', [GrantReleaseController::class, 'update'])->name('grant-releases.update');
    Route::delete('/grant-releases/{grantRelease}', [GrantReleaseController::class, 'destroy'])->name('grant-releases.destroy');
    Route::get('/settings/profile', [ProfileController::class, 'edit'])->name('settings.profile.edit');
    Route::put('/settings/profile', [ProfileController::class, 'update'])->name('settings.profile.update');
    Route::get('/settings/captcha', [CaptchaSettingsController::class, 'edit'])->name('settings.captcha.edit');
    Route::put('/settings/captcha', [CaptchaSettingsController::class, 'update'])->name('settings.captcha.update');
    Route::get('/settings/divisions', [DivisionController::class, 'index'])->name('settings.divisions.index');
    Route::post('/settings/divisions', [DivisionController::class, 'store'])->name('settings.divisions.store');
    Route::get('/settings/divisions/{division}/edit', [DivisionController::class, 'edit'])->name('settings.divisions.edit');
    Route::put('/settings/divisions/{division}', [DivisionController::class, 'update'])->name('settings.divisions.update');
    Route::delete('/settings/divisions/{division}', [DivisionController::class, 'destroy'])->name('settings.divisions.destroy');
    Route::get('/settings/districts', [DistrictController::class, 'index'])->name('settings.districts.index');
    Route::post('/settings/districts', [DistrictController::class, 'store'])->name('settings.districts.store');
    Route::get('/settings/districts/{district}/edit', [DistrictController::class, 'edit'])->name('settings.districts.edit');
    Route::put('/settings/districts/{district}', [DistrictController::class, 'update'])->name('settings.districts.update');
    Route::delete('/settings/districts/{district}', [DistrictController::class, 'destroy'])->name('settings.districts.destroy');
    Route::get('/settings/departments', [DepartmentController::class, 'index'])->name('settings.departments.index');
    Route::post('/settings/departments', [DepartmentController::class, 'store'])->name('settings.departments.store');
    Route::get('/settings/departments/{department}/edit', [DepartmentController::class, 'edit'])->name('settings.departments.edit');
    Route::put('/settings/departments/{department}', [DepartmentController::class, 'update'])->name('settings.departments.update');
    Route::delete('/settings/departments/{department}', [DepartmentController::class, 'destroy'])->name('settings.departments.destroy');
    Route::get('/settings/roles', [RoleController::class, 'index'])->name('settings.roles.index');
    Route::get('/settings/roles/create', [RoleController::class, 'create'])->name('settings.roles.create');
    Route::post('/settings/roles', [RoleController::class, 'store'])->name('settings.roles.store');
    Route::get('/settings/roles/{role}/edit', [RoleController::class, 'edit'])->name('settings.roles.edit');
    Route::put('/settings/roles/{role}', [RoleController::class, 'update'])->name('settings.roles.update');
    Route::put('/settings/roles/{role}/details', [RoleController::class, 'updateDetails'])->name('settings.roles.details.update');
    Route::put('/settings/roles/{role}/access', [RoleController::class, 'updateAccess'])->name('settings.roles.access.update');
    Route::delete('/settings/roles/{role}', [RoleController::class, 'destroy'])->name('settings.roles.destroy');
    Route::get('/logs/security-logs', [SecurityLogController::class, 'index'])->name('logs.security.index');
    Route::delete('/logs/security-logs/months', [SecurityLogController::class, 'deleteMonthsLogs'])->name('logs.security.delete-months');
    Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
});
